Read and write methods working with a timeout
JuliaIO/LibSerialPort.jl pull request #94
Opened 2023-05-10 20:56 UTC by stepanoslejsek

I recently discovered that the already implemented read and write methods do not trigger the set timeout. I went through the source code and implemented additional read and write methods with the number of bytes that need to be read or written.

Using these methods, the timeout was triggered and the exception was handled as it should be.

2023-05-11 08:57 UTC, mgkuhn requested changes
You can't just redefine
```
function write(sp::SerialPort, nb::UInt, b::UInt8)
```
because [the standard `Base.write(io::IO, x1, xs...)` Julia meaning of that method](write(sp, 0x0000000000000000, 0x01)) is to output the binary representation of a `UInt` value followed by a `UInt8` value, and `LibSerialPorts` just implements the normal `IO` interface. Your change would cause a very nasty surprise to anyone trying to call e.g.
```
write(sp, 0x0000000000000000, 0x01)
```

Likewise, what does your new read method give you that e.g. `Base.readbytes!` doesn't?

Could you please explain first what problem you are trying to solve, with a concrete test example, because I suspect your PR is the result of a misunderstanding of how LibSerialPort extends the existing `IO` methods of `Base`, rather than tries to reimplement that interface from scratch.

2023-05-11 14:55 UTC, mgkuhn commented
Doesn't [`read!(::IO, ::Array{UInt8})`](https://github.com/JuliaLang/julia/blob/6618d4416d23c71c676cd697a99df6ef63d0e2ae/base/io.jl#LL774C24-L774C38) already do exactly what you need?

Example:
```
using LibSerialPort
sp = LibSerialPort.open("/dev/ttyUSB0", 9600)
set_flow_control(sp)
sp_flush(sp, SP_BUF_BOTH)
timeout = 2
set_read_timeout(sp, timeout)
request = UInt8[1,2,3,4,5,6,7,8]
reply = Vector{UInt8}(undef, 20)
write(sp, request)
try
  read!(sp, reply)
catch e
    if isa(e, LibSerialPort.Timeout)
        println("Timed out after $timeout seconds")
    else
        rethrow()
    end
end
clear_read_timeout(sp)
print(reply)
```

However, I just realized that [the docstring of `read!`](::Array{UInt8}) doesn't actually describe how to use it.

If the above example solves your problem, I think improving the docstring in `Base` is the solution, rather than this PR.

2023-05-11 17:55 UTC, mgkuhn commented
PR for improved docstring of `read!` in `Base`: https://github.com/JuliaLang/julia/pull/49769

2023-05-11 20:29 UTC, stepanoslejsek commented
> 

I am gonna try this, thank you, I will let know if it works or not.

2023-05-19 09:38 UTC, stepanoslejsek commented
> clear_read_timeout(sp)

This exactly worked, thank you for brief explanation.

2023-05-19 11:51 UTC, mgkuhn commented
Thanks for reporting back. I'll close this PR here, as the main improvement needed appears to be the docstring of `read!` in `Base`.

2023-05-19 11:51 UTC, closed without merging